import mongoose from "mongoose";
import { User, Instructor, Student, Collaborator, Partner } from "../types";
import { validateEmail, validatePhoneNumber } from "./validators";
import bcrypt from "bcryptjs";

const googleSchema = new mongoose.Schema(
  {
    id: { type: String, required: false },
    name: { type: String, required: false },
    email: { type: String, required: false },
    image: { type: String, required: false },
    email_verified: { type: Boolean, required: false },
  },
  { _id: false }
);

const linkedinSchema = new mongoose.Schema(
  {
    sub: { type: String, required: false },
    name: { type: String, required: false },
    given_name: { type: String, required: false },
    family_name: { type: String, required: false },
    image: { type: String, required: false },
    locale: { type: String, required: false },
    providerAccountId: { type: String, required: false },
    email: { type: String, required: false },
    email_verified: { type: Boolean, required: false },
    id_token: { type: String, required: false },
    accessToken: { type: String, required: false },
  },
  { _id: false }
);

const socialProfilesSchema = new mongoose.Schema(
  {
    google: { type: googleSchema, required: false },
    linkedin: { type: linkedinSchema, required: false },
    github: { type: String, required: false },
    instagram: { type: String, required: false },
  },
  { _id: false }
);

const addressSchema = new mongoose.Schema(
  {
    address: { type: String, required: false },
    city: { type: String, required: false },
    state: { type: String, required: false },
    country: { type: String, required: false },
    pincode: { type: String, required: false },
  },
  { _id: false }
);

const previousExperienceDurationSchema = new mongoose.Schema(
  {
    from: { type: Date, required: true },
    to: { type: Date, required: true },
  },
  { _id: false }
);

const previousExperienceSchema = new mongoose.Schema(
  {
    companyName: { type: String, required: true },
    position: { type: String, required: true },
    duration: { type: previousExperienceDurationSchema, required: true },
    description: { type: String, required: true },
  },
  { _id: false }
);

/**
 * Sub-schema for each entry in `successPointsHistory`.
 * `_id` is auto-generated by MongoDB (ObjectId) — no manual `id` field needed.
 * All optional fields cover the three transaction types: earned, transferred_in, transferred_out.
 */
const successPointCourseSnapshotSchema = new mongoose.Schema(
  {
    title: { type: String, required: true },
    slug:  { type: String, required: false },
  },
  { _id: false }
);

const successPointTransactionSchema = new mongoose.Schema(
  {
    transactionId: { type: String, required: true }, // uuid generated at award time
    earnedAt:  { type: Date,   required: true },
    type:      { type: String, required: true, enum: ["earned", "transferred_in", "transferred_out", "admin_adjustment", "redeemed", "reward"] },
    // Signed for "admin_adjustment" (negative = deduction); a positive
    // magnitude for every other type.
    points:    { type: Number, required: true },
    // "earned" fields
    courseId:       { type: mongoose.Schema.Types.ObjectId, ref: "Course",      required: false },
    enrollmentId:   { type: mongoose.Schema.Types.ObjectId, ref: "Enrollment",  required: false },
    earnSource:     { type: String, required: false },
    courseSnapshot: { type: successPointCourseSnapshotSchema, required: false },
    // "transferred_in" fields
    fromUserId:          { type: mongoose.Schema.Types.ObjectId, ref: "User", required: false },
    fromUserDisplayName: { type: String, required: false },
    // "transferred_out" fields
    toUserId:          { type: mongoose.Schema.Types.ObjectId, ref: "User", required: false },
    toUserDisplayName: { type: String, required: false },
    // shared transfer field
    peerTransactionId: { type: String, required: false },
    // "admin_adjustment" fields
    adjustedByUserId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: false },
    adjustedByName:   { type: String, required: false },
    // "redeemed" field — orderId is what links a redemption to its purchase
    orderId: { type: mongoose.Schema.Types.ObjectId, ref: "Order", required: false },
    // "reward" field — which milestone event granted the points
    rewardSource: { type: String, required: false },
  },
  { _id: false } // transactionId is the explicit identifier; no auto _id needed
);

const userSchema = new mongoose.Schema<User>(
  {
    status: {
      type: String,
      required: true,
      enum: ["active", "inactive", "blocked"],
      default: "active",
    },
    firstName: { type: String, required: false },
    lastName: { type: String, required: false },
    profilePicture: { type: String, required: false },
    email: {
      type: String,
      required: true,
      unique: true,
      validate: {
        validator: validateEmail,
        message: "Please enter a valid email address.",
      },
    },
    phone: {
      type: String,
      required: false,
      validate: {
        validator: validatePhoneNumber,
        message:
          "Please enter a valid phone number — 10 digits, or +91 followed by your number.",
      },
    },
    whatsappNumber: {
      type: String,
      required: false,
      validate: {
        validator: validatePhoneNumber,
        message:
          "Please enter a valid WhatsApp number — 10 digits, or +91 followed by your number.",
      },
    },
    password: { type: String, required: true, select: false },
    userType: {
      type: String,
      required: true,
      enum: [
        "student",
        "instructor",
        "collaborator",
        "partner",
        "admin",
        "super-admin",
      ],
      default: "student",
    },
    provider: {
      type: String,
      enum: ["credentials", "google", "linkedin"],
      default: "credentials",
      required: true,
    },
    address: {
      type: addressSchema,
      required: false,
    },
    accounts: {
      type: socialProfilesSchema,
      required: true,
      default: {},
    },
    dob: { type: Date, required: false },
    gender: {
      type: String,
      enum: ["male", "female", "other"],
      required: false,
    },
    permissions: {
      type: [String],
      required: true,
      default: [],
    },
    refreshTokens: [
      {
        token: { type: String, required: true },
        deviceInfo: {
          userAgent: { type: String, required: false },
          ipAddress: { type: String, required: false },
          deviceType: { type: String, required: false },
        },
        createdAt: { type: Date, default: Date.now },
        lastUsed: { type: Date, default: Date.now },
        isActive: { type: Boolean, default: true },
        expiresAt: {
          type: Date,
          default: () => new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days from now
          required: true,
        },
      },
    ],
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now },
  },
  {
    discriminatorKey: "userType",
    timestamps: true,
  }
);

// Add middleware to update the updatedAt field before saving
userSchema.pre("save", function (next) {
  this.updatedAt = new Date();
  next();
});

// Add middleware to update the updatedAt field before updating
userSchema.pre("findOneAndUpdate", function (next) {
  this.set({ updatedAt: new Date() });
  next();
});

// Add middleware to update the updatedAt field before updating
userSchema.pre("updateOne", function (next) {
  this.set({ updatedAt: new Date() });
  next();
});

// Add middleware to update the updatedAt field before updating
userSchema.pre("updateMany", function (next) {
  this.set({ updatedAt: new Date() });
  next();
});

// Create the base User model
const UserModel = mongoose.model<User>("User", userSchema);

// Instructor discriminator schema
const instructorSchema = new mongoose.Schema<Instructor>({
  slug: {
    type: String,
    required: false,
    trim: true,
  },
  rating: {
    type: Number,
    required: true,
    default: 0,
    min: 0,
    max: 5,
  },
  totalStudents: {
    type: Number,
    required: true,
    default: 0,
    min: 0,
  },
  bio: { type: String, required: false },
  industry: { type: String, required: false, trim: true },
  companyImages: {
    type: [String],
    required: false,
    default: [],
  },
  field: { type: String, required: false },
  currentPosition: { type: String, required: false },
  currentCompany: { type: String, required: false },
  previousExperience: {
    type: [previousExperienceSchema],
    required: false,
    default: [],
  },
  linkedinUrl: {
    type: String,
    required: false,
    validate: {
      validator: function (v: string) {
        if (!v) return true; // Allow empty string
        return /^https?:\/\/(www\.)?linkedin\.com\/in\/[a-zA-Z0-9-]+\/?$/.test(
          v
        );
      },
      message: "Invalid LinkedIn URL format",
    },
  },
  reviews: {
    type: [mongoose.Schema.Types.ObjectId],
    ref: "Review",
    required: false,
    default: [],
  },
  ownedCourses: {
    type: [mongoose.Schema.Types.ObjectId],
    ref: "Course",
    required: false,
    default: [],
  },
});

// Unique slug for instructors only (sparse allows other user types)
instructorSchema.index({ slug: 1 }, { unique: true, sparse: true });

// Student discriminator schema
const studentSchema = new mongoose.Schema<Student>({
  enrollments: {
    type: [mongoose.Schema.Types.ObjectId],
    ref: "Enrollment",
    required: false,
    default: [],
  },
  // Canonical link to the College directory. New writes set this from the
  // CollegeSelect dropdown's `_id`. `collegeName` is kept as a denormalised
  // snapshot so the display survives if the linked College is later deleted
  // or renamed (the cascade in college.services.ts unsets `college` but
  // leaves `collegeName` intact).
  college: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "College",
    required: false,
  },
  collegeName: { type: String, required: false },
  degreeName: { type: String, required: false },
  fatherOccupation: { type: String, required: false },
  experienceLevel: { type: String, required: false },
  passingYear: {
    type: Number,
    required: false,
    min: 1900,
    max: new Date().getFullYear() + 10,
  },
  areaOfInterest: { type: String, required: false },
  experience: { type: [previousExperienceSchema], required: false },
  currentPosition: { type: String, required: false },
  currentCompany: { type: String, required: false },
  domain: { type: String, required: false },
  // Free-text LinkedIn profile URL entered by the learner (e.g. on the
  // internship enrollment form). The OAuth provider snapshot lives in
  // `accounts.linkedin` and is separate.
  linkedinUrl: {
    type: String,
    required: false,
    trim: true,
    validate: {
      validator: function (v: string) {
        if (!v) return true;
        return /^https?:\/\/(www\.)?linkedin\.com\/.+/.test(v);
      },
      message: "Invalid LinkedIn URL format",
    },
  },
  portfolio: {
    type: String,
    required: false,
    validate: {
      validator: function (v: string) {
        if (!v) return true; // Allow empty
        return /^https?:\/\/.+/.test(v); // Basic URL validation
      },
      message: "Portfolio must be a valid URL",
    },
  },
  // Joining info
  joinSource: {
    type: String,
    enum: ["direct", "affiliate", "promotion"],
    required: false,
  },
  affiliation: {
    isAffiliate: {
      type: Boolean,
      required: false,
      default: false,
    },
    affiliate: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Affiliate",
      required: false,
    },
  },
  // Orders
  orders: {
    type: [mongoose.Schema.Types.ObjectId],
    ref: "Order",
    required: false,
    default: [],
  },
  // Pending payments
  pendingPayments: {
    type: [mongoose.Schema.Types.ObjectId],
    ref: "Order",
    required: false,
    default: [],
  },
  // No `min` — an admin adjustment may intentionally push a balance negative.
  successPoints: { type: Number, required: false, default: 0 },
  successPointsHistory: {
    type: [successPointTransactionSchema],
    default: [],
  },
  /** One-shot idempotency flag for the first-login wallet bonus. */
  firstLoginBonusAwarded: { type: Boolean, required: false, default: false },
});

// Collaborator discriminator schema
const collaboratorSchema = new mongoose.Schema<Collaborator>({
  totalReferrals: {
    type: Number,
    required: true,
    default: 0,
    min: 0,
  },
  totalEarnings: {
    type: Number,
    required: true,
    default: 0,
    min: 0,
  },
});

// Partner discriminator schema (college-side partner portal users).
// Links to an existing College document by ObjectId — same directory the
// students pick from in their profile, so admins don't have to maintain a
// separate partner-only list. Cascade lives in college.services.ts:
// deleting a college deactivates every partner pointing at it.
// Schema is intentionally not generically typed with <Partner> because
// `partnerCollege` is an ObjectId at the storage layer but typed as `string`
// in the Partner interface (it's serialised across the wire to the frontend).
// Mongoose's generic strict-match rejects that mismatch; dropping the generic
// preserves runtime correctness without sprinkling casts.
const partnerSchema = new mongoose.Schema({
  partnerCollege: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "College",
    required: [true, "College is required for partner users"],
    validate: {
      validator: async function (
        value: mongoose.Types.ObjectId,
      ): Promise<boolean> {
        if (!value) return false;
        const College = mongoose.model("College");
        const exists = await College.exists({ _id: value });
        return Boolean(exists);
      },
      message: (props: { value: unknown }) =>
        `College "${String(props.value)}" does not exist`,
    },
  },
  /** Admin gate: when true the partner can open the Courses analytics page. */
  courseAnalyticsEnabled: { type: Boolean, required: true, default: true },
  /** Admin gate: when true the partner can open the Internships analytics page. */
  internshipAnalyticsEnabled: { type: Boolean, required: true, default: true },
});

// Create discriminator models
const InstructorModel = UserModel.discriminator<Instructor>(
  "instructor",
  instructorSchema
);
const StudentModel = UserModel.discriminator<Student>("student", studentSchema);
const CollaboratorModel = UserModel.discriminator<Collaborator>(
  "collaborator",
  collaboratorSchema
);
const PartnerModel = UserModel.discriminator<Partner>("partner", partnerSchema);

// reset password
userSchema.statics.resetPassword = async function (
  id: string,
  password: string
) {
  const user = await this.findById(id).select("+password");
  if (!user) {
    throw new Error("User not found");
  }
  const hashedPassword = await bcrypt.hash(password, 10);
  user.password = hashedPassword;
  await user.save();
  return user;
};

export {
  UserModel,
  InstructorModel,
  StudentModel,
  CollaboratorModel,
  PartnerModel,
};
