import mongoose from "mongoose";
import { User, Instructor, Student, Collaborator, Partner } from "../types";
import { validateEmail, validatePhoneNumber } from "./validators";
import bcrypt from "bcryptjs";

const googleSchema = new mongoose.Schema(
  {
    id: { type: String, required: false },
    name: { type: String, required: false },
    email: { type: String, required: false },
    image: { type: String, required: false },
    email_verified: { type: Boolean, required: false },
  },
  { _id: false }
);

const linkedinSchema = new mongoose.Schema(
  {
    sub: { type: String, required: false },
    name: { type: String, required: false },
    given_name: { type: String, required: false },
    family_name: { type: String, required: false },
    image: { type: String, required: false },
    locale: { type: String, required: false },
    providerAccountId: { type: String, required: false },
    email: { type: String, required: false },
    email_verified: { type: Boolean, required: false },
    id_token: { type: String, required: false },
    accessToken: { type: String, required: false },
  },
  { _id: false }
);

const socialProfilesSchema = new mongoose.Schema(
  {
    google: { type: googleSchema, required: false },
    linkedin: { type: linkedinSchema, required: false },
    github: { type: String, required: false },
    instagram: { type: String, required: false },
  },
  { _id: false }
);

const addressSchema = new mongoose.Schema(
  {
    address: { type: String, required: false },
    city: { type: String, required: false },
    state: { type: String, required: false },
    country: { type: String, required: false },
    pincode: { type: String, required: false },
  },
  { _id: false }
);

const previousExperienceDurationSchema = new mongoose.Schema(
  {
    from: { type: Date, required: true },
    to: { type: Date, required: true },
  },
  { _id: false }
);

const previousExperienceSchema = new mongoose.Schema(
  {
    companyName: { type: String, required: true },
    position: { type: String, required: true },
    duration: { type: previousExperienceDurationSchema, required: true },
    description: { type: String, required: true },
  },
  { _id: false }
);

/**
 * Sub-schema for each entry in `successPointsHistory`.
 * `_id` is auto-generated by MongoDB (ObjectId) — no manual `id` field needed.
 * All optional fields cover the three transaction types: earned, transferred_in, transferred_out.
 */
const successPointCourseSnapshotSchema = new mongoose.Schema(
  {
    title: { type: String, required: true },
    slug:  { type: String, required: false },
  },
  { _id: false }
);

const successPointTransactionSchema = new mongoose.Schema(
  {
    transactionId: { type: String, required: true }, // uuid generated at award time
    earnedAt:  { type: Date,   required: true },
    type:      { type: String, required: true, enum: ["earned", "transferred_in", "transferred_out", "admin_adjustment", "redeemed", "reward", "expired"] },
    // Signed for "admin_adjustment" (negative = deduction); a positive
    // magnitude for every other type.
    points:    { type: Number, required: true },
    // "earned" fields
    courseId:       { type: mongoose.Schema.Types.ObjectId, ref: "Course",      required: false },
    enrollmentId:   { type: mongoose.Schema.Types.ObjectId, ref: "Enrollment",  required: false },
    earnSource:     { type: String, required: false },
    courseSnapshot: { type: successPointCourseSnapshotSchema, required: false },
    // "transferred_in" fields
    fromUserId:          { type: mongoose.Schema.Types.ObjectId, ref: "User", required: false },
    fromUserDisplayName: { type: String, required: false },
    // "transferred_out" fields
    toUserId:          { type: mongoose.Schema.Types.ObjectId, ref: "User", required: false },
    toUserDisplayName: { type: String, required: false },
    // shared transfer field
    peerTransactionId: { type: String, required: false },
    // "admin_adjustment" fields
    adjustedByUserId: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: false },
    adjustedByName:   { type: String, required: false },
    // Expiry the admin chose on a grant; null means never.
    expiresAt: { type: Date, required: false },
    // "redeemed" field — orderId is what links a redemption to its purchase
    orderId: { type: mongoose.Schema.Types.ObjectId, ref: "Order", required: false },
    // "reward" field — which milestone event granted the points
    rewardSource: { type: String, required: false },
  },
  { _id: false } // transactionId is the explicit identifier; no auto _id needed
);

const successPointLotSchema = new mongoose.Schema(
  {
    points: { type: Number, required: true, min: 1 },
    expiresAt: { type: Date, required: false, default: null },
  },
  { _id: false }
);

const userSchema = new mongoose.Schema<User>(
  {
    status: {
      type: String,
      required: true,
      enum: ["active", "inactive", "blocked"],
      default: "active",
    },
    firstName: { type: String, required: false },
    lastName: { type: String, required: false },
    profilePicture: { type: String, required: false },
    email: {
      type: String,
      required: true,
      unique: true, 
      lowercase: true,
      trim: true,
      validate: {
        validator: validateEmail,
        message: "Please enter a valid email address.",
      },
    },
    phone: {
      type: String,
      required: false,
      validate: {
        validator: validatePhoneNumber,
        message:
          "Please enter a valid phone number — 10 digits, or +91 followed by your number.",
      },
    },
    /**
     * When the number in `phone` was last proven by an MSG91 OTP. Unset on
     * accounts created before phone verification existed, and on numbers an
     * admin wrote directly, so it means "proven by the owner", not "present".
     */
    phoneVerifiedAt: { type: Date, required: false },
    whatsappNumber: {
      type: String,
      required: false,
      validate: {
        validator: validatePhoneNumber,
        message:
          "Please enter a valid WhatsApp number — 10 digits, or +91 followed by your number.",
      },
    },
    password: { type: String, required: true, select: false },
    /**
     * When the password was last changed from inside the account, and when the
     * email was last moved. Both gate a cooldown on doing it again.
     *
     * Absent on every account that predates the cooldown, which the check
     * reads as "never changed, allow it" rather than backfilling a date that
     * would lock existing learners out of a change they never made.
     */
    passwordChangedAt: { type: Date, required: false },
    emailChangedAt: { type: Date, required: false },
    userType: {
      type: String,
      required: true,
      enum: [
        "student",
        "instructor",
        "collaborator",
        "partner",
        "marketer",
        "sales",
        "admin",
        "super-admin",
      ],
      default: "student",
    },
    provider: {
      type: String,
      enum: ["credentials", "google", "linkedin"],
      default: "credentials",
      required: true,
    },
    address: {
      type: addressSchema,
      required: false,
    },
    accounts: {
      type: socialProfilesSchema,
      required: true,
      default: {},
    },
    dob: { type: Date, required: false },
    gender: {
      type: String,
      enum: ["male", "female", "other"],
      required: false,
    },
    permissions: {
      type: [String],
      required: true,
      default: [],
    },
    /**
     * Platforms this person has joined. Absent on accounts that predate the
     * brand split, which count as Airkrit.
     */
    brands: {
      type: [{ type: String, enum: ["airkrit", "edulyt"] }],
      required: true,
      default: () => ["airkrit"],
    },
    refreshTokens: [
      {
        // SHA-256 hash of the opaque refresh token (never store the plaintext).
        tokenHash: { type: String, required: true },
        // Rotation lineage: set once at login, copied on every rotation.
        family: { type: String, required: true },
        deviceInfo: {
          userAgent: { type: String, required: false },
          ipAddress: { type: String, required: false },
          deviceType: { type: String, required: false },
        },
        createdAt: { type: Date, default: Date.now },
        lastUsed: { type: Date, default: Date.now },
        // When this token was rotated out; within the grace window it still works.
        rotatedAt: { type: Date, default: null },
        isActive: { type: Boolean, default: true },
        // Sliding idle expiry — bumped on each rotation.
        idleExpiresAt: { type: Date, required: true },
        // Hard cap — fixed at first login, never moves.
        absoluteExpiresAt: { type: Date, required: true },
      },
    ],
    /**
     * Opt-outs for non-essential email. Absent means subscribed, so existing
     * accounts need no backfill and only an explicit `false` suppresses a send.
     * Transactional mail ignores this entirely.
     */
    emailPreferences: {
      reviews: { type: Boolean, required: false, default: true },
      referrals: { type: Boolean, required: false, default: true },
      promotions: { type: Boolean, required: false, default: true },
    },
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now },
  },
  {
    discriminatorKey: "userType",
    timestamps: true,
  }
);

// Add middleware to update the updatedAt field before saving
userSchema.pre("save", function (next) {
  this.updatedAt = new Date();
  next();
});

// Add middleware to update the updatedAt field before updating
userSchema.pre("findOneAndUpdate", function (next) {
  this.set({ updatedAt: new Date() });
  next();
});

// Add middleware to update the updatedAt field before updating
userSchema.pre("updateOne", function (next) {
  this.set({ updatedAt: new Date() });
  next();
});

// Add middleware to update the updatedAt field before updating
userSchema.pre("updateMany", function (next) {
  this.set({ updatedAt: new Date() });
  next();
});

// Phone verification looks the number up across every account to stop two
// learners from claiming it. Sparse because most legacy accounts have no phone
// and an unindexed lookup would scan the whole users collection on every send.
userSchema.index({ phone: 1 }, { sparse: true });
// Staff pickers filter by role and status then sort by name. Without this the
// lookup scans every user, and the collection is mostly students.
userSchema.index({ userType: 1, status: 1, firstName: 1 });
// The admin panel filters the user list by brand membership.
userSchema.index({ brands: 1, userType: 1, status: 1 });
// Create the base User model
const UserModel = mongoose.model<User>("User", userSchema);

// Instructor discriminator schema
const instructorSchema = new mongoose.Schema<Instructor>({
  slug: {
    type: String,
    required: false,
    trim: true,
  },
  rating: {
    type: Number,
    required: true,
    default: 0,
    min: 0,
    max: 5,
  },
  totalStudents: {
    type: Number,
    required: true,
    default: 0,
    min: 0,
  },
  bio: { type: String, required: false },
  industry: { type: String, required: false, trim: true },
  companyImages: {
    type: [String],
    required: false,
    default: [],
  },
  field: { type: String, required: false },
  currentPosition: { type: String, required: false },
  currentCompany: { type: String, required: false },
  previousExperience: {
    type: [previousExperienceSchema],
    required: false,
    default: [],
  },
  linkedinUrl: {
    type: String,
    required: false,
    validate: {
      validator: function (v: string) {
        if (!v) return true; // Allow empty string
        return /^https?:\/\/(www\.)?linkedin\.com\/in\/[a-zA-Z0-9-]+\/?$/.test(
          v
        );
      },
      message: "Invalid LinkedIn URL format",
    },
  },
  reviews: {
    type: [mongoose.Schema.Types.ObjectId],
    ref: "Review",
    required: false,
    default: [],
  },
  ownedCourses: {
    type: [mongoose.Schema.Types.ObjectId],
    ref: "Course",
    required: false,
    default: [],
  },
});

// Unique slug for instructors only (sparse allows other user types)
instructorSchema.index({ slug: 1 }, { unique: true, sparse: true });

// Student discriminator schema
const studentSchema = new mongoose.Schema<Student>({
  enrollments: {
    type: [mongoose.Schema.Types.ObjectId],
    ref: "Enrollment",
    required: false,
    default: [],
  },
  // Canonical link to the College directory. New writes set this from the
  // CollegeSelect dropdown's `_id`. `collegeName` is kept as a denormalised
  // snapshot so the display survives if the linked College is later deleted
  // or renamed (the cascade in college.services.ts unsets `college` but
  // leaves `collegeName` intact).
  college: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "College",
    required: false,
  },
  collegeName: { type: String, required: false },
  degreeName: { type: String, required: false },
  fatherOccupation: { type: String, required: false },
  experienceLevel: { type: String, required: false },
  passingYear: {
    type: Number,
    required: false,
    min: 1900,
    max: new Date().getFullYear() + 10,
  },
  areaOfInterest: { type: String, required: false },
  experience: { type: [previousExperienceSchema], required: false },
  currentPosition: { type: String, required: false },
  currentCompany: { type: String, required: false },
  domain: { type: String, required: false },
  // Free-text LinkedIn profile URL entered by the learner (e.g. on the
  // internship enrollment form). The OAuth provider snapshot lives in
  // `accounts.linkedin` and is separate.
  linkedinUrl: {
    type: String,
    required: false,
    trim: true,
    validate: {
      validator: function (v: string) {
        if (!v) return true;
        return /^https?:\/\/(www\.)?linkedin\.com\/.+/.test(v);
      },
      message: "Invalid LinkedIn URL format",
    },
  },
  portfolio: {
    type: String,
    required: false,
    validate: {
      validator: function (v: string) {
        if (!v) return true; // Allow empty
        return /^https?:\/\/.+/.test(v); // Basic URL validation
      },
      message: "Portfolio must be a valid URL",
    },
  },
  // Joining info
  joinSource: {
    type: String,
    enum: ["direct", "affiliate", "promotion"],
    required: false,
  },
  affiliation: {
    isAffiliate: {
      type: Boolean,
      required: false,
      default: false,
    },
    affiliate: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Affiliate",
      required: false,
    },
  },
  // Orders
  orders: {
    type: [mongoose.Schema.Types.ObjectId],
    ref: "Order",
    required: false,
    default: [],
  },
  // Pending payments
  pendingPayments: {
    type: [mongoose.Schema.Types.ObjectId],
    ref: "Order",
    required: false,
    default: [],
  },
  // No `min` — an admin adjustment may intentionally push a balance negative.
  successPoints: { type: Number, required: false, default: 0 },
  successPointsHistory: {
    type: [successPointTransactionSchema],
    default: [],
  },
  successPointsLots: { type: [successPointLotSchema], default: undefined },
  // Compare-and-set guard: every wallet write rewrites the lots array.
  successPointsVersion: { type: Number, required: false, default: 0 },
  successPointsTransferMonth: { type: String, required: false },
  successPointsTransferredThisMonth: { type: Number, required: false, default: 0 },
  /** One-shot idempotency flag for the first-login wallet bonus. */
  firstLoginBonusAwarded: { type: Boolean, required: false, default: false },
});

// Multikey index on the wallet ledger's timestamps. Lets the admin
// success-points report pre-select only the students holding at least one
// transaction inside the requested date range, instead of unwinding the whole
// students collection. Sparse: students who never transacted carry an empty
// array and are not worth indexing.
studentSchema.index({ "successPointsHistory.earnedAt": 1 }, { sparse: true });
studentSchema.index({ "successPointsLots.expiresAt": 1 }, { sparse: true });

// Collaborator discriminator schema
const collaboratorSchema = new mongoose.Schema<Collaborator>({
  totalReferrals: {
    type: Number,
    required: true,
    default: 0,
    min: 0,
  },
  totalEarnings: {
    type: Number,
    required: true,
    default: 0,
    min: 0,
  },
});

// Partner discriminator schema (college-side partner portal users).
// Links to an existing College document by ObjectId — same directory the
// students pick from in their profile, so admins don't have to maintain a
// separate partner-only list. Cascade lives in college.services.ts:
// deleting a college deactivates every partner pointing at it.
// Schema is intentionally not generically typed with <Partner> because
// `partnerCollege` is an ObjectId at the storage layer but typed as `string`
// in the Partner interface (it's serialised across the wire to the frontend).
// Mongoose's generic strict-match rejects that mismatch; dropping the generic
// preserves runtime correctness without sprinkling casts.
const partnerSchema = new mongoose.Schema({
  partnerCollege: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "College",
    required: [true, "College is required for partner users"],
    validate: {
      validator: async function (
        value: mongoose.Types.ObjectId,
      ): Promise<boolean> {
        if (!value) return false;
        const College = mongoose.model("College");
        const exists = await College.exists({ _id: value });
        return Boolean(exists);
      },
      message: (props: { value: unknown }) =>
        `College "${String(props.value)}" does not exist`,
    },
  },
  /** Admin gate: when true the partner can open the Courses analytics page. */
  courseAnalyticsEnabled: { type: Boolean, required: true, default: true },
  /** Admin gate: when true the partner can open the Internships analytics page. */
  internshipAnalyticsEnabled: { type: Boolean, required: true, default: true },
});

// Marketer discriminator schema. Carries no fields of its own: the role exists
// so scholarship access is a userType rather than a permissions grant, which
// keeps marketers out of every other admin surface by construction.
const marketerSchema = new mongoose.Schema({});

// Sales discriminator schema. Fieldless for the same reason as marketer: the
// role is the grant, so a sales user holds no permissions array that could be
// widened to reach another admin surface.
const salesSchema = new mongoose.Schema({});

// Create discriminator models
const InstructorModel = UserModel.discriminator<Instructor>(
  "instructor",
  instructorSchema
);
const StudentModel = UserModel.discriminator<Student>("student", studentSchema);
const CollaboratorModel = UserModel.discriminator<Collaborator>(
  "collaborator",
  collaboratorSchema
);
const PartnerModel = UserModel.discriminator<Partner>("partner", partnerSchema);
const MarketerModel = UserModel.discriminator("marketer", marketerSchema);
const SalesModel = UserModel.discriminator("sales", salesSchema);

// reset password
userSchema.statics.resetPassword = async function (
  id: string,
  password: string
) {
  const user = await this.findById(id).select("+password");
  if (!user) {
    throw new Error("User not found");
  }
  const hashedPassword = await bcrypt.hash(password, 10);
  user.password = hashedPassword;
  // Starts the change cooldown. A reset is a password change like any other, so
  // leaving it unstamped would let a learner reset, then immediately change
  // again from the profile, and the limit would only ever bind the second half
  // of that pair.
  user.passwordChangedAt = new Date();
  await user.save();
  return user;
};

export {
  UserModel,
  InstructorModel,
  StudentModel,
  CollaboratorModel,
  PartnerModel,
  MarketerModel,
  SalesModel,
};
