import type { IconOption } from "./internshipIcons";

export const TRAINING_PILLAR_ICONS: IconOption[] = [
  { name: "mdi:teach", label: "Teaching" },
  { name: "mdi:book-edit-outline", label: "Curriculum" },
  { name: "mdi:account-voice", label: "Mentorship" },
  { name: "mdi:laptop-account", label: "Live Sessions" },
  { name: "mdi:hammer-wrench", label: "Hands-on" },
  { name: "mdi:account-group-outline", label: "Cohort" },
  { name: "mdi:projector-screen-outline", label: "Workshops" },
  { name: "mdi:notebook-outline", label: "Notes" },
  { name: "mdi:school-outline", label: "Education" },
  { name: "mdi:chart-arc", label: "Analytics" },
  { name: "mdi:lightbulb-on-outline", label: "Ideas" },
  { name: "mdi:certificate-outline", label: "Certificate" },
  { name: "mdi:trophy-outline", label: "Achievement" },
  { name: "mdi:rocket-launch-outline", label: "Growth" },
  { name: "mdi:check-decagram-outline", label: "Quality" },
  { name: "mdi:cog-outline", label: "Tools" },
  { name: "mdi:database-outline", label: "Data" },
  { name: "mdi:chart-line", label: "Progress" },
  { name: "mdi:code-tags", label: "Code" },
  { name: "mdi:office-building-outline", label: "Industry" },
  { name: "mdi:briefcase-outline", label: "Work Experience" },
  { name: "mdi:account-tie", label: "Expert" },
  { name: "mdi:target", label: "Goal" },
  { name: "mdi:robot-outline", label: "AI" },
  { name: "mdi:brain", label: "Knowledge" },
  { name: "mdi:flask-outline", label: "Experiment" },
  { name: "mdi:test-tube", label: "Test Lab" },
  { name: "mdi:puzzle-outline", label: "Problem Solving" },
  { name: "mdi:book-open-page-variant", label: "Learning Material" },
  { name: "mdi:video-outline", label: "Video Content" },
];

export const PREPARE_ITEM_ICONS: IconOption[] = [
  { name: "mdi:file-document-edit-outline", label: "Resume" },
  { name: "mdi:account-tie-voice", label: "Interview Prep" },
  { name: "mdi:test-tube", label: "Mock Tests" },
  { name: "mdi:office-building-outline", label: "Company Insight" },
  { name: "mdi:linkedin", label: "LinkedIn" },
  { name: "mdi:account-search-outline", label: "Job Search" },
  { name: "mdi:handshake-outline", label: "Networking" },
  { name: "mdi:presentation", label: "Presentation" },
  { name: "mdi:format-list-checks", label: "Checklist" },
  { name: "mdi:chart-bar", label: "Performance" },
  { name: "mdi:briefcase-search-outline", label: "Placement" },
  { name: "mdi:account-supervisor-outline", label: "HR Skills" },
  { name: "mdi:book-account-outline", label: "Portfolio" },
  { name: "mdi:laptop", label: "Online Practice" },
  { name: "mdi:certificate-outline", label: "Certification" },
  { name: "mdi:account-star-outline", label: "Personal Brand" },
  { name: "mdi:message-text-outline", label: "Communication" },
  { name: "mdi:lightbulb-outline", label: "Aptitude" },
  { name: "mdi:human-greeting-variant", label: "Soft Skills" },
  { name: "mdi:database-search-outline", label: "Domain Knowledge" },
  { name: "mdi:chart-timeline-variant", label: "Career Roadmap" },
  { name: "mdi:rocket-launch-outline", label: "Career Launch" },
  { name: "mdi:target-arrow", label: "Targeted Prep" },
  { name: "mdi:calendar-check-outline", label: "Schedule" },
  { name: "mdi:bookmark-check-outline", label: "Goals" },
  { name: "mdi:file-find-outline", label: "Job Description" },
  { name: "mdi:account-voice", label: "Group Discussion" },
  { name: "mdi:medal-outline", label: "Recognition" },
  { name: "mdi:notebook-edit-outline", label: "Journal" },
  { name: "mdi:trending-up", label: "Career Growth" },
];
