import { Course } from "@/types";

export const demoCourses: Course[] = [
  {
    id: "1",
    isActive: true,
    title: "Complete Python Data Science Bootcamp", 
    description: "Master Python, Data Science, Machine Learning, and more",
    thumbnail: "https://www.newdev.io/images/blog/python-functions-for-beginners/thumbnail.webp",
    previewVideoUrl: "/videos/web-dev-preview.mp4",
    isFeatured: true,
    isCertified: true,
    totalRatings: 2847,
    enrolledCount: 15420,
    totalLectures: 120,
    skillLevel: "Beginner",
    category: "professionals",
    instructor: [
      {
        id: "inst-1",
        name: "Sarah Johnson",
        profileImage: "/instructors/sarah.jpg",
        experience: "8 years of Experience",
        rating: 4.9,
        totalStudents: 25000,
        totalCourses: 12,
        bio: "Full-stack developer and educator",
        linkedinUrl: "https://linkedin.com/in/sarahjohnson",
      },
    ],
    lastUpdated: new Date("2024-01-15"),
    language: "English",
    whatYouWillLearn: ["HTML & CSS", "JavaScript", "React", "Node.js"],
    whoShouldJoin: "Aspiring web developers and college students",
    prerequisites: ["Basic computer skills"],
    modules: [],
    plan: {
      professionals: {
        name: "Professional Plan",
        price: 199.99,
        features: ["Full access", "Certificate", "1-on-1 mentoring"],
      },
      collegeStudents: {
        name: "Student Plan",
        price: 99.99,
        features: ["Full access", "Certificate", "Student support"],
      },
    },
    featuredReviews: [],
    features: ["Hands-on projects", "Industry-relevant curriculum"],
    faqs: [],
    createdAt: new Date("2023-06-01"),
    updatedAt: new Date("2024-01-15"),
    createdBy: "admin",
    slug: "complete-python-data-science-bootcamp",
    curriculumDescription: "Comprehensive web development curriculum",
  },
];
