export const demoCourses = [
  {
    id: "1",
    title: "Data Science: Zero to Hundred",
    image: "/CourseCardDemo.jpg",
    bestSeller: true,
    enrollStudents: "100",
    rating: 4.5,
    totalRating: 100,
    mentors: [
      {
        name: "Dr. Sarah Johnson",
        image: "/CourseCardDemo.jpg",
      },
    ],
    startingPrice: 100,
    category: "Data Science",
    discount: 50,
  },
  {
    id: "2",
    title: "Advanced Machine Learning Algorithms",
    image: "/CourseCardDemo.jpg",
    bestSeller: false,
    enrollStudents: "250",
    rating: 4.8,
    totalRating: 150,
    mentors: [
      {
        name: "Prof. Michael Chen",
        image: "/CourseCardDemo.jpg",
      },
    ],
    startingPrice: 120,
    category: "Machine Learning",
    discount: 30,
  },
  {
    id: "3",
    title: "Artificial Intelligence Fundamentals",
    image: "/CourseCardDemo.jpg",
    bestSeller: true,
    enrollStudents: "180",
    rating: 4.7,
    totalRating: 95,
    mentors: [
      {
        name: "Dr. Alex Rodriguez",
        image: "/CourseCardDemo.jpg",
      },
    ],
    startingPrice: 150,
    category: "AI",
    discount: 40,
  },
  {
    id: "4",
    title: "Full Stack Web Development Bootcamp",
    image: "/CourseCardDemo.jpg",
    bestSeller: true,
    enrollStudents: "300",
    rating: 4.6,
    totalRating: 200,
    mentors: [
      {
        name: "John Smith",
        image: "/CourseCardDemo.jpg",
      },
      {
        name: "Emma Wilson",
        image: "/CourseCardDemo.jpg",
      },
    ],
    startingPrice: 80,
    category: "Web Development",
    discount: 25,
  },
  {
    id: "5",
    title: "React & Next.js Masterclass",
    image: "/CourseCardDemo.jpg",
    bestSeller: false,
    enrollStudents: "150",
    rating: 4.4,
    totalRating: 80,
    mentors: [
      {
        name: "Lisa Anderson",
        image: "/CourseCardDemo.jpg",
      },
    ],
    startingPrice: 90,
    category: "Web Development",
    discount: 20,
  },
  {
    id: "6",
    title: "Deep Learning with Python",
    image: "/CourseCardDemo.jpg",
    bestSeller: false,
    enrollStudents: "120",
    rating: 4.9,
    totalRating: 110,
    mentors: [
      {
        name: "Dr. Kevin Park",
        image: "/CourseCardDemo.jpg",
      },
    ],
    startingPrice: 140,
    category: "Machine Learning",
    discount: 35,
  },
  {
    id: "7",
    title: "Data Visualization with D3.js",
    image: "/CourseCardDemo.jpg",
    bestSeller: false,
    enrollStudents: "90",
    rating: 4.3,
    totalRating: 75,
    mentors: [
      {
        name: "Maria Garcia",
        image: "/CourseCardDemo.jpg",
      },
    ],
    startingPrice: 75,
    category: "Data Science",
    discount: 15,
  },
  {
    id: "8",
    title: "Computer Vision with AI",
    image: "/CourseCardDemo.jpg",
    bestSeller: true,
    enrollStudents: "200",
    rating: 4.7,
    totalRating: 160,
    mentors: [
      {
        name: "Dr. James Liu",
        image: "/CourseCardDemo.jpg",
      },
    ],
    startingPrice: 160,
    category: "AI",
    discount: 45,
  },
];
